# markdown: kramdown
markdown: redcarpet
# markdown: rdiscount

kramdown:
  entity_output: symbolic
  input: GFM

redcarpet:
  extensions: [smart, autolink, strikethrough, no_intra_emphasis, tables]

encoding: utf-8

baseurl: /TimeBench

exclude:
- README.md
- Gemfile
- Gemfile.lock

# GitHub set these settings anyway
safe: true
lsi: false
pygments: true

