markdown: kramdown
# markdown: redcarpet
# markdown: rdiscount

kramdown:
  entity_output: symbolic
  input: GFM

encoding: utf-8

baseurl: /TimeBench

exclude:
- README.md
- Gemfile
- Gemfile.lock

# GitHub set these settings anyway
safe: true
lsi: false
pygments: true

